# Generated by Django 2.2.14 on 2020-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200715_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='first_name',
            field=models.CharField(default='lolz', max_length=100),
            preserve_default=False,
        ),
    ]
